name: hero_here
description: "Hero transitions on the same screen without the need for navigation."
version: 1.0.2
homepage: https://github.com/igorkurilenko/hero_here

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
